const API_URL="https://script.google.com/macros/s/AKfycbwqqBJ1A9tqYhPhEJe37Ik3-HGKZOHUUHqdf_jtLJuTv8tqQpt6WqX5jUBQwKPMbM92tw/exec";
const BADGE_PRESETS=["Promo","Hot Promo","Limited","Best Deal","Mega Sale","Promo Raya","Promo Merdeka","Promo Gaji","Last Call","Custom"];
const BADGE_COLORS=["Gold","Green","Red","Blue","Purple","Dark"];
const BASE_PRODUCTS=[
{name:"NETFLIX PREMIUM",section:"ALL",plans:[{duration:"1 Bulan",price:"RM25"},{duration:"2 Bulan",price:"RM45"},{duration:"3 Bulan Promo",price:"RM60"},{duration:"6 Bulan",price:"RM120"},{duration:"12 Bulan",price:"RM230"}]},
{name:"YOUTUBE PREMIUM",section:"Email Sendiri",plans:[{duration:"1 Bulan",price:"RM16"},{duration:"3 Bulan",price:"RM45"},{duration:"6 Bulan",price:"RM85"},{duration:"12 Bulan",price:"RM144"}]},
{name:"YOUTUBE PREMIUM",section:"Email Seller",plans:[{duration:"1 Bulan",price:"RM10"},{duration:"3 Bulan",price:"RM27"},{duration:"6 Bulan",price:"RM48"},{duration:"12 Bulan",price:"RM84"}]},
{name:"DISNEY+ HOTSTAR",section:"ALL",plans:[{duration:"1 Bulan",price:"RM25"},{duration:"2 Bulan",price:"RM45"},{duration:"Promo 3 Bulan",price:"RM60"},{duration:"6 Bulan",price:"RM120"},{duration:"12 Bulan",price:"RM230"}]},
{name:"SOOKA PREMIUM",section:"ALL",plans:[{duration:"1 Bulan",price:"RM25"},{duration:"2 Bulan",price:"RM46"},{duration:"6 Bulan",price:"RM120"},{duration:"12 Bulan",price:"RM216"}]},
{name:"VIU PREMIUM",section:"ALL",plans:[{duration:"1 Bulan",price:"RM15"},{duration:"2 Bulan",price:"RM26"},{duration:"6 Bulan",price:"RM66"},{duration:"12 Bulan",price:"RM120"}]},
{name:"iQIYI PREMIUM",section:"ALL",plans:[{duration:"1 Bulan",price:"RM15"},{duration:"2 Bulan",price:"RM26"},{duration:"Promo 3 Bulan",price:"RM33"},{duration:"6 Bulan",price:"RM66"},{duration:"12 Bulan",price:"RM120"}]},
{name:"SPOTIFY PREMIUM",section:"ALL",plans:[{duration:"1 Bulan",price:"RM15"},{duration:"2 Bulan",price:"RM28"},{duration:"Promo 2 Bulan",price:"RM25"},{duration:"6 Bulan",price:"RM72"},{duration:"12 Bulan",price:"RM120"}]}
];
let data={stock:[],promos:[],meta:{}};let pass=sessionStorage.getItem("numoAdminPassword")||"";let logged=!!pass;const $=id=>document.getElementById(id);
const els={};document.addEventListener("DOMContentLoaded",()=>{["loginCard","panelCard","adminPassword","loginBtn","loginMessage","globalMessage","logoutBtn","refreshBtnTop","stockGrid","promoGrid","promoSearch","clearPromoSearch","summaryStockOn","summaryStockOff","summaryPromoActive","lastSync"].forEach(id=>els[id]=$(id));bind();if(pass)els.adminPassword.value=pass;if(logged){showPanel();load();}});
function bind(){els.loginBtn.onclick=login;els.adminPassword.onkeydown=e=>{if(e.key==="Enter")login()};els.logoutBtn.onclick=logout;els.refreshBtnTop.onclick=()=>logged?load():msg(els.loginMessage,"Login dulu.","info");document.querySelectorAll(".tab-btn").forEach(b=>b.onclick=()=>tab(b.dataset.tab));els.promoSearch.oninput=renderPromos;els.clearPromoSearch.onclick=()=>{els.promoSearch.value="";renderPromos()};}
async function login(){const p=els.adminPassword.value.trim();if(!p)return msg(els.loginMessage,"Masukkan password dulu.","error");busy(els.loginBtn,true,"Checking...");try{const r=await post({mode:"verifyAdmin",password:p});if(!r.ok)throw new Error(r.error||"Password salah");pass=p;logged=true;sessionStorage.setItem("numoAdminPassword",p);showPanel();msg(els.globalMessage,"Login berjaya.","success");await load();}catch(e){msg(els.loginMessage,"Login gagal: "+e.message,"error")}finally{busy(els.loginBtn,false,"Login Admin")}}
function logout(){pass="";logged=false;sessionStorage.removeItem("numoAdminPassword");els.panelCard.classList.remove("active");els.loginCard.style.display="block";els.logoutBtn.classList.add("hidden");els.adminPassword.value="";msg(els.loginMessage,"Logout berjaya.","info")}
function showPanel(){els.loginCard.style.display="none";els.panelCard.classList.add("active");els.logoutBtn.classList.remove("hidden")}
async function load(){msg(els.globalMessage,"Loading data dari Google Sheet...","info");busy(els.refreshBtnTop,true,"Loading");try{const r=await fetch(API_URL+"?mode=getWebsiteControl&_="+Date.now()).then(x=>x.json());if(!r.ok)throw new Error(r.error||"Gagal baca data");data=r.data||{stock:[],promos:[],meta:{}};renderDashboard();renderStock();renderPromos();msg(els.globalMessage,"Data berjaya sync.","success")}catch(e){msg(els.globalMessage,"Gagal load data: "+e.message,"error")}finally{busy(els.refreshBtnTop,false,"Refresh")}}
function renderDashboard(){els.summaryStockOn.textContent=data.stock.filter(x=>norm(x.status)==="ON").length;els.summaryStockOff.textContent=data.stock.filter(x=>norm(x.status)==="OFF").length;els.summaryPromoActive.textContent=data.promos.filter(isActive).length;els.lastSync.textContent="Last sync: "+new Date().toLocaleString("ms-MY")}
function renderStock(){if(!data.stock.length){els.stockGrid.innerHTML='<div class="empty-state">Tiada data stock.</div>';return}const order=["NETFLIX PREMIUM||ALL","YOUTUBE PREMIUM||Email Sendiri","YOUTUBE PREMIUM||Email Seller","DISNEY+ HOTSTAR||ALL","SOOKA PREMIUM||ALL","VIU PREMIUM||ALL","iQIYI PREMIUM||ALL","SPOTIFY PREMIUM||ALL"];const arr=[...data.stock].sort((a,b)=>(order.indexOf(a.product+"||"+a.section)+999)%999-(order.indexOf(b.product+"||"+b.section)+999)%999);els.stockGrid.innerHTML=arr.map((x,i)=>{const st=norm(x.status)==="OFF"?"OFF":"ON";return `<article class="stock-item"><div class="stock-top"><div><div class="product-title">${safe(x.product)}</div><div class="product-section">${safe(x.section==="ALL"?"Semua plan":x.section)}</div></div><span class="pill ${st==="ON"?"on":"off"}">${st==="ON"?"ON":"HABIS STOK"}</span></div><div class="stock-form"><div class="form-row"><div><label class="field-label">Status Produk</label><select class="select stock-status"><option value="ON" ${st==="ON"?"selected":""}>ON - Boleh Order</option><option value="OFF" ${st==="OFF"?"selected":""}>OFF - Habis Stok</option></select></div><div><label class="field-label">Text bila habis stok</label><input class="input stock-text" value="${attr(x.stockText||"Habis Stok")}"></div></div><div class="quick-row"><button class="btn green on-btn" type="button">Ada Stok</button><button class="btn red off-btn" type="button">Habis Stok</button><button class="btn gold save-btn" type="button">Save Stock</button></div></div></article>`}).join("");els.stockGrid.querySelectorAll(".stock-item").forEach((card,i)=>{const x=arr[i];card.querySelector(".on-btn").onclick=()=>{card.querySelector(".stock-status").value="ON";card.querySelector(".stock-text").value="Habis Stok"};card.querySelector(".off-btn").onclick=()=>{card.querySelector(".stock-status").value="OFF";card.querySelector(".stock-text").value="Habis Stok"};card.querySelector(".save-btn").onclick=()=>saveStock(card,x);});}
async function saveStock(card,x){const btn=card.querySelector(".save-btn");busy(btn,true,"Saving...");try{const payload={stock:[{product:x.product,section:x.section||"ALL",status:card.querySelector(".stock-status").value,stockText:card.querySelector(".stock-text").value.trim()||"Habis Stok"}]};const r=await post({mode:"saveWebsiteControl",password:pass,payload:JSON.stringify(payload)});if(!r.ok)throw new Error(r.error||"Gagal save");msg(els.globalMessage,"Stock berjaya disimpan.","success");await load()}catch(e){msg(els.globalMessage,"Gagal save stock: "+e.message,"error")}finally{busy(btn,false,"Save Stock")}}
function flatten(){return BASE_PRODUCTS.flatMap(p=>p.plans.map(pl=>({product:p.name,section:p.section,duration:pl.duration,normalPrice:pl.price})))}
function findPromo(p,s,d){return data.promos.find(x=>norm(x.product)===norm(p)&&norm(x.section||"ALL")===norm(s||"ALL")&&norm(x.duration)===norm(d))}
function renderPromos(){const q=norm(els.promoSearch.value);let items=flatten().map(pl=>Object.assign({},pl,findPromo(pl.product,pl.section,pl.duration)||{promoActive:"NO",promoPrice:"",badgePreset:"Promo",badgeCustomText:"",badgeColor:"Gold",note:""}));if(q)items=items.filter(x=>norm(`${x.product} ${x.section} ${x.duration} ${x.normalPrice}`).includes(q));if(!items.length){els.promoGrid.innerHTML='<div class="empty-state">Tiada plan dijumpai.</div>';return}els.promoGrid.innerHTML=items.map((x,i)=>promoCard(x)).join("");els.promoGrid.querySelectorAll(".promo-item").forEach((card,i)=>wirePromo(card,items[i]));}
function promoCard(x){const active=isActive(x)?"YES":"NO",preset=x.badgePreset||"Promo",custom=x.badgeCustomText||"",color=x.badgeColor||"Gold",badge=preset==="Custom"?(custom||"Promo"):preset;return `<article class="promo-item"><div class="promo-top"><div><div class="product-title">${safe(x.product)} • ${safe(x.duration)}</div><div class="product-section">${safe(x.section==="ALL"?"Semua plan":x.section)} • Harga asal ${safe(x.normalPrice)}</div></div><span class="pill ${active==="YES"?"promo":"off"}">${active==="YES"?"PROMO ON":"PROMO OFF"}</span></div><div class="promo-form"><div class="price-line"><span>Preview:</span><span class="normal-price">${safe(x.normalPrice)}</span><span class="promo-price-preview">${safe(x.promoPrice||x.normalPrice)}</span><span class="badge-preview ${badgeClass(color)}">${safe(badge)}</span></div><div class="form-row"><div><label class="field-label">Promo Active</label><select class="select promo-active"><option value="NO" ${active==="NO"?"selected":""}>OFF</option><option value="YES" ${active==="YES"?"selected":""}>ON</option></select></div><div><label class="field-label">Promo Price</label><input class="input promo-price" placeholder="Contoh: RM20" value="${attr(x.promoPrice||"")}"></div></div><div class="form-row"><div><label class="field-label">Badge Preset</label><select class="select badge-preset">${BADGE_PRESETS.map(o=>`<option value="${attr(o)}" ${o===preset?"selected":""}>${safe(o)}</option>`).join("")}</select></div><div><label class="field-label">Badge Color</label><select class="select badge-color">${BADGE_COLORS.map(o=>`<option value="${attr(o)}" ${o===color?"selected":""}>${safe(o)}</option>`).join("")}</select></div></div><div class="custom-badge-wrap ${preset==="Custom"?"":"hidden"}"><label class="field-label">Custom Badge Text</label><input class="input badge-custom-text" placeholder="Contoh: Promo Weekend" value="${attr(custom)}"></div><div><label class="field-label">Promo Note</label><textarea class="textarea promo-note" placeholder="Contoh: Promo bulan ini sementara slot masih ada">${safe(x.note||"")}</textarea></div><div class="quick-row"><button class="btn green promo-on" type="button">Promo ON</button><button class="btn soft promo-off" type="button">Promo OFF</button><button class="btn red promo-clear" type="button">Clear</button></div><button class="btn gold promo-save" type="button">Save Promo</button></div></article>`}
function wirePromo(card,x){const active=card.querySelector(".promo-active"),price=card.querySelector(".promo-price"),preset=card.querySelector(".badge-preset"),customWrap=card.querySelector(".custom-badge-wrap"),custom=card.querySelector(".badge-custom-text"),color=card.querySelector(".badge-color"),note=card.querySelector(".promo-note"),badge=card.querySelector(".badge-preview"),preview=card.querySelector(".promo-price-preview");function update(){customWrap.classList.toggle("hidden",preset.value!=="Custom");badge.textContent=preset.value==="Custom"?(custom.value.trim()||"Promo"):preset.value;badge.className="badge-preview "+badgeClass(color.value);preview.textContent=price.value.trim()||x.normalPrice}[active,price,preset,custom,color,note].forEach(el=>el.addEventListener("input",update));preset.addEventListener("change",update);color.addEventListener("change",update);card.querySelector(".promo-on").onclick=()=>{active.value="YES";if(!price.value.trim())price.value=x.normalPrice;update()};card.querySelector(".promo-off").onclick=()=>{active.value="NO";update()};card.querySelector(".promo-clear").onclick=()=>{active.value="NO";price.value="";preset.value="Promo";custom.value="";color.value="Gold";note.value="";update()};card.querySelector(".promo-save").onclick=()=>savePromo(card,x);update()}
async function savePromo(card,x){const btn=card.querySelector(".promo-save"),active=card.querySelector(".promo-active").value,price=card.querySelector(".promo-price").value.trim(),preset=card.querySelector(".badge-preset").value,custom=card.querySelector(".badge-custom-text").value.trim(),color=card.querySelector(".badge-color").value,note=card.querySelector(".promo-note").value.trim();if(active==="YES"&&!price)return msg(els.globalMessage,"Isi Promo Price dulu.","error");if(preset==="Custom"&&!custom)return msg(els.globalMessage,"Isi Custom Badge Text dulu.","error");busy(btn,true,"Saving...");try{const payload={promos:[{product:x.product,section:x.section||"ALL",duration:x.duration,promoActive:active,promoPrice:price,badgePreset:preset,badgeCustomText:custom,badgeColor:color,note}]};const r=await post({mode:"saveWebsiteControl",password:pass,payload:JSON.stringify(payload)});if(!r.ok)throw new Error(r.error||"Gagal save");msg(els.globalMessage,"Promo berjaya disimpan.","success");await load()}catch(e){msg(els.globalMessage,"Gagal save promo: "+e.message,"error")}finally{busy(btn,false,"Save Promo")}}
async function post(obj){const body=new URLSearchParams();Object.entries(obj).forEach(([k,v])=>body.append(k,v));const res=await fetch(API_URL,{method:"POST",body});return res.json()}
function tab(name){document.querySelectorAll(".tab-btn").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));document.querySelectorAll(".section-block").forEach(s=>s.classList.toggle("active",s.id===name))}
function isActive(x){return ["YES","ON","TRUE"].includes(norm(x.promoActive))}function badgeClass(c){c=norm(c);if(c==="GREEN")return"badge-green";if(c==="RED")return"badge-red";if(c==="BLUE")return"badge-blue";if(c==="PURPLE"||c==="PINK")return"badge-purple";if(c==="DARK"||c==="BLACK")return"badge-dark";return"badge-gold"}
function busy(btn,on,text){if(!btn)return;if(on){btn.dataset.txt=btn.textContent;btn.textContent=text||"Loading...";btn.disabled=true}else{btn.textContent=btn.dataset.txt||text||btn.textContent;btn.disabled=false}}function msg(el,m,type="info"){el.textContent=m;el.className="status-message show "+type;if(type==="success"){clearTimeout(el.t);el.t=setTimeout(()=>el.classList.remove("show"),4500)}}function norm(v=""){return String(v||"").trim().toUpperCase()}function safe(v=""){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function attr(v=""){return safe(v)}
